# Generated by Django 3.1.3 on 2020-11-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
