# Generated by Django 3.1.3 on 2020-11-05 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_auto_20201105_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='long_id',
        ),
        migrations.AlterField(
            model_name='friend',
            name='friendship_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 12, 12, 17, 177135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='receivedrequest',
            name='received_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 12, 12, 17, 177135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sentrequest',
            name='sent_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 12, 12, 17, 177135, tzinfo=utc)),
        ),
    ]
