# Generated by Django 3.1.3 on 2020-11-05 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0012_auto_20201105_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(default=True)),
                ('long_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='long_id',
        ),
        migrations.AlterField(
            model_name='friend',
            name='friendship_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 12, 14, 56, 135934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='receivedrequest',
            name='received_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 12, 14, 56, 135934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sentrequest',
            name='sent_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 12, 14, 56, 135934, tzinfo=utc)),
        ),
    ]
