# Generated by Django 3.1.3 on 2020-11-05 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0015_auto_20201105_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='long_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friendship_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 12, 25, 24, 308176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='receivedrequest',
            name='received_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 12, 25, 24, 308176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sentrequest',
            name='sent_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 12, 25, 24, 308176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='long_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
