# Generated by Django 3.1.3 on 2020-11-06 22:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0020_auto_20201106_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendship_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 22, 29, 49, 491757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.usersystem'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 22, 29, 49, 496757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 22, 29, 49, 496757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='receivedrequest',
            name='received_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 22, 29, 49, 491757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sentrequest',
            name='sent_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 22, 29, 49, 491757, tzinfo=utc)),
        ),
    ]
