# Generated by Django 3.1.3 on 2020-11-14 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0022_auto_20201113_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendship_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 22, 56, 52, 669794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 22, 56, 52, 669794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 22, 56, 52, 669794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='receivedrequest',
            name='received_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 22, 56, 52, 669794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sentrequest',
            name='sent_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 22, 56, 52, 669794, tzinfo=utc)),
        ),
    ]
